# -*- coding: utf-8 -*-
"""iris_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MFJAo5zvdkd2hfGzFyK9dQV6Z1-pDdT3
"""



import streamlit as st
import pandas as pd
import numpy as np
import joblib


model = joblib.load('knn(1).joblib')

# Step 4: Streamlit layout and user input for flower dimensions
st.title("Iris Flower Species Prediction")
st.write("This app predicts the species of an iris flower based on its features.")

# Input fields for the user to enter flower dimensions
sepal_length = st.number_input('Sepal Length (cm)', min_value=0.0, max_value=10.0, value=5.0, step=0.1)
sepal_width = st.number_input('Sepal Width (cm)', min_value=0.0, max_value=10.0, value=3.0, step=0.1)
petal_length = st.number_input('Petal Length (cm)', min_value=0.0, max_value=10.0, value=4.0, step=0.1)
petal_width = st.number_input('Petal Width (cm)', min_value=0.0, max_value=10.0, value=1.0, step=0.1)

# Step 5: Make prediction when the user presses the "Predict" button
if st.button('Predict Species'):
    input_data = np.array([[sepal_length, sepal_width, petal_length, petal_width]])

    # Make prediction
    prediction = knn.predict(input_data)

    # Display the predicted species
    species = iris.target_names[prediction[0]]
    st.write(f"The predicted species is: {species}")

    # Evaluate and display model accuracy
    y_pred = knn.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    st.write(f"Model Accuracy: {accuracy * 100:.2f}%")
